name: BLS Data Validation

on:
  pull_request:
    paths:
      - 'docs/bls-data/**'

jobs:
  validate_json_raw:
    name: Validate JSON (Raw)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Clean install dependencies and build
      run: |
        npm ci
        npm run build --if-present
    - name: Run validation script
      run: npm run-script validate-json-raw
  validate_json_prospect:
    name: Validate JSON (Prospect)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Clean install dependencies and build
      run: |
        npm ci
        npm run build --if-present
    - name: Run validation script
      run: npm run-script validate-json-prospect


    