# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BLS data intake

on:
  push:
    branches: 
      - 'data/intake'
    paths:
      - 'docs/bls-data/**.xlsx'

jobs:
  generate_timestamp:
    name: Generate intake timestamp
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{  steps.generate_timestamp.outputs.TIMESTAMP  }}
    steps:
    - name: Generate timestamp
      run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
  intake_conversion:
    name: Convert intake file
    needs: generate_timestamp
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{  needs.generate_timestamp.outputs.timestamp  }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Clean install dependencies and build
      run: |
        npm ci
        npm run build --if-present
    - name: Convert XLSX to JSON
      run: npm run-script convert-xlsx
    - name: Commit converted files
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/bls-data/wc-bls-data-raw.json
        git add docs/bls-data/wc-bls-data-prospect.json
        git commit -m "Update BLS JSON files ${{ env.TIMESTAMP }}"
        git push
  validate_json_raw:
    name: Validate raw JSON
    needs: intake_conversion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Clean install dependencies and build
      run: |
        npm ci
        npm run build --if-present
    - name: Run validation script
      run: npm run-script validate-json-raw
  validate_json_prospect:
    name: Validate prospect JSON
    needs: intake_conversion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Clean install dependencies and build
      run: |
        npm ci
        npm run build --if-present
    - name: Run validation script
      run: npm run-script validate-json-prospect
  create_pr:
    name: Create pull request
    needs: [generate_timestamp, validate_json_raw, validate_json_prospect]
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{  needs.generate_timestamp.outputs.timestamp  }}
    steps:
    - name: Create pull request through GitHub CLI
      run: gh pr create --title "Update BLS data ${{ env.TIMESTAMP }}" --body "Update BLS data JSON files from new XLSX file" --base main --assignee zri5004 --reviewer zri5004 --label data-intake
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}