# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "data/intake" ]
  pull_request:
    branches: [ "data/intake" ]

jobs:
  convert-xlsx:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run-script convert-xlsx
  create-pr:
    name: Create pull request
    runs-on: ubuntu-latest
    needs: convert-xlsx
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get current datetime
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update BLS data ${{ steps.date.outputs.date }}
          title: Update BLS data ${{ steps.date.outputs.date }}
          body: Update BLS JSON data from XLSX file.
          branch: data/test