# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
      - 'data/intake'
      - '!main'
    paths:
      - 'bls-data/**'

jobs:
  # convert-xlsx:
  #   name: Convert XLSX to JSON
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npm ci
  #   - run: npm run build --if-present
  #   - run: npm run-script convert-xlsx
  create-timestamp:
    name: Get datetime
    runs-on: ubuntu-latest
    steps:
    - name: Get current datetime
      run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')" >> ${GITHUB_ENV}
    - run: echo "Timestamp set to " . ${{ env.TIMESTAMP }}
  # commit-files:
  #   name: Commit converted files
  #   runs-on: ubuntu-latest
  #   needs: [create-timestamp, convert-xlsx]
  #   steps:
  #   - run: echo git config --list
  #   - run: git add bls-data/wc-bls-data-sample.json
  #   - run: git commit -m "Update BLS JSON files"
  #   - run: git push
  # create-pr:
  #   name: Create pull request
  #   runs-on: ubuntu-latest
  #   needs: [create-timestamp, commit-files]
  #   steps:
  #   - name: Create pull request
  #     uses: peter-evans/create-pull-request@v7
  #     with:
  #       commit-message: Update BLS data ${{ env.TIMESTAMP }}
  #       title: Update BLS data ${{ env.TIMESTAMP }}
  #       body: Update BLS JSON data from XLSX file.
  #       branch: data/test










  # - name: Get current datetime
  #       id: date
  #       run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
  # convert-xlsx:

  #   runs-on: ubuntu-latest
  #   if: ${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }}
  #   strategy:
  #     matrix:
  #       # node-version: [18.x, 20.x, 22.x]
  #       node-version: [22.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm ci
  #   - run: npm run build --if-present
  #   - run: npm run-script convert-xlsx
  #   - name: commit and push
  #     run: git config --list
  #       git add bls-data/wc-bls-data-sample.json
  #       git commit -m "Update BLS JSON files"
  #       git push
  # create-pr:
  #   name: Create pull request
  #   runs-on: ubuntu-latest
  #   needs: convert-xlsx
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
      
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v7
  #       with:
  #         commit-message: Update BLS data ${{ steps.date.outputs.date }}
  #         title: Update BLS data ${{ steps.date.outputs.date }}
  #         body: Update BLS JSON data from XLSX file.
  #         branch: data/test