name: XLSX Data Conversion/Validation

on: 
  push:
    branches: 
      - data-intake

jobs: 
  convert_xlsx:
    name: Convert XLSX to JSON
    runs-on: ubuntu-latest
    steps: 
      #conversion
  create_artifact:
    name: Create JSON artifact
    needs: convert_xlsx
  validate_json:
    name: Validate JSON
    runs-on: ubuntu-latest
    needs: create_artifact
    steps: 
  create_pr:
    name: Create pull request
    runs-on: ubuntu-latest
    needs: validate_json
    steps:
      - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      # - name: Update AUTHORS
      #   run: |
      #     git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: update json
          title: Update JSON
          body: Update JSON with new valid data
          branch: data/test
          